name: Python Code Quality 
 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  security-events: write

jobs:
  pre-commit-checks:
    name: Pre-Commit Gate
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      status: ${{ steps.check.result }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run security checks
        run: |
          pip install pre-commit
          pre-commit run --all-files --show-diff-on-failure 

  testing:
    name: Unit Testing
    needs: pre-commit-checks
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1 libegl1 xvfb
        pip install -e .
        pip install pytest pytest-cov 

    - name: Run tests
      run: |
        pytest --cov=./ --cov-report=xml:coverage.xml  ./linearheart/tests/

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml

  complexity-analysis:
    name: Code Complexity
    needs: pre-commit-checks
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Install Radon
      run: pip install radon

    - name: Analyze complexity
      run: |
        radon cc --min C -n D --total-average . > radon-report.txt  
        radon raw --summary . >> radon-report.txt

    - name: Upload complexity report
      uses: actions/upload-artifact@v4
      with:
        name: radon-complexity-report
        path: radon-report.txt