name: Python Code Quality 
 
on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'doc/**'
      - 'radon-report.txt'
  pull_request:
    branches: [main]

permissions:
  contents: write
  security-events: write

jobs:
  code-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.local/lib/python3.12/site-packages
        key: ${{ runner.os  }}-python-${{ hashFiles('**/requirements.txt')  }}-v3

    - name: Install toolchain
      run: |
        python -m pip install --upgrade pip
        pip install autoflake black isort mypy radon
      env:
        PATH: ${{ env.PATH }}:/opt/hostedtoolcache/Python/3.12.5/x64/bin

    - name: Auto-format code
      run: |
        autoflake --in-place --remove-all-unused-imports --remove-unused-variables -r .
        isort --profile black --atomic .
        black --line-length 120 --target-version py312 --safe .

    - name: Static type checking
      run: mypy --ignore-missing-imports --explicit-package-bases .

    - name: Complexity analysis
      run: |
        radon cc --min C -n D --total-average . > radon-report.txt  
        radon raw --summary . >> radon-report.txt

    - name: Commit formatting
      if: github.event_name  == 'push'
      run: |
        git config --global user.name  "Xiangyuan Xie"
        git config --global user.email  "dragonboat_xxy@163.com" 
        git add .
        git diff --quiet HEAD || git commit -m "CI: Auto-format code"
        git push